name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4    
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Set ENV vars
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV      
    - name: My step
      run: echo "COMMIT_URL=`echo https://github.com/kratochj/personal-page/commit/${GITHUB_SHA}`" >> $GITHUB_ENV
#    - name: Setup Gradle
#      uses: gradle/gradle-build-action@v2      
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: apps/personal-page
        tags: 1, latest, ${{ env.SHORT_SHA }}
        registry: ${{ vars.DOCKER_REGISTRY }}
        dockerfile: Dockerfile
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        enableBuildKit: true
        labels: "commit=${{ env.SHORT_SHA }}"
    - name: Webhook
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: ${{ secrets.PORTAINER_WEBHOOK }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}        
