name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Get GH SHA
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV      
    - name: Get commit URL
      run: echo "COMMIT_URL=`echo https://github.com/kratochj/personal-page/commit/${GITHUB_SHA}`" >> $GITHUB_ENV
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: apps/personal-page
        tags: 1, latest, ${{ env.SHORT_SHA }}
        registry: ${{ vars.DOCKER_REGISTRY }}
        dockerfile: Dockerfile
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        enableBuildKit: true
        labels: "commit=${{ env.COMMIT_URL }}"
